version: '3.8'

services:
  api:
    build: .
    container_name: smartcontract-backend
    ports:
      - '3001:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: smartcontract-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpassword
      POSTGRES_DB: smartcontract
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 