version: '3.8'

services:
  api:
    build: .
    container_name: smartcontract-backend
    ports:
      - '3001:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: smartcontract-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpassword
      POSTGRES_DB: smartcontract
      POSTGRES_MULTIPLE_DATABASES: smartcontract,smartcontract_readonly
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smartcontract-pgadmin
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin_data: 